1

In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


2:Scalar & Array Operations

In [2]:
#Scalar & Array Operations
scalar = 3.7
arr = np.array([2, 4, 6, 8, 3, 5])
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)

sin: [ 0.90929743 -0.7568025  -0.2794155   0.98935825  0.14112001 -0.95892427]
cos: [-0.41614684 -0.65364362  0.96017029 -0.14550003 -0.9899925   0.28366219]
tan: [-2.18503986  1.15782128 -0.29100619 -6.79971146 -0.14254654 -3.38051501]
asin: [0.25268026 0.52359878 0.84806208 1.57079633 0.38439677 0.67513153]
acos: [1.31811607 1.04719755 0.72273425 0.         1.18639955 0.89566479]
atan: [1.10714872 1.32581766 1.40564765 1.44644133 1.24904577 1.37340077]


3:Creating a 3x2 matrix

In [3]:
# Creating a 3x2 matrix

matrix = np.array([[-1.79, -2], [3.6, 4.45], [5.12, -6.33]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[-1.79 -2.  ]
 [ 3.6   4.45]
 [ 5.12 -6.33]]

sin:
 [[-0.97607092 -0.90929743]
 [-0.44252044 -0.96577306]
 [-0.91807047 -0.04679759]]

cos:
 [[-0.21745242 -0.41614684]
 [-0.89675842 -0.2593885 ]
 [ 0.39641721  0.99890439]]

tan:
 [[ 4.48866432  2.18503986]
 [ 0.49346673  3.72326857]
 [-2.31591983 -0.04684892]]

asine:
 [[-0.35715414 -0.40131044]
 [ 0.77978281  1.05346202]
 [ 1.57079633 -1.57079633]]

acosine:
 [[1.92795046 1.97210676]
 [0.79101352 0.51733431]
 [0.         3.14159265]]

atangent:
 [[-1.06132928 -1.10714872]
 [ 1.29984948  1.34974926]
 [ 1.37791201 -1.41411333]]

exp:
 [[1.66960170e-01 1.35335283e-01]
 [3.65982344e+01 8.56269440e+01]
 [1.67335370e+02 1.78203377e-03]]

log (natural):
 [[       nan        nan]
 [1.28093385 1.4929041 ]
 [1.63315444        nan]]

abs:
 [[1.79 2.  ]
 [3.6  4.45]
 [5.12 6.33]]

sqrt:
 [[       nan        nan]
 [1.8973666  2.10950231]
 [2.2627417         nan]]

rem (remainder when divided by 2):
 [[0.21 0.  ]
 [1.6  0.45]
 [1.12 1.67]

/tmp/ipython-input-2706135316.py:15: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)  # Natural logarithm (log base e)
/tmp/ipython-input-2706135316.py:19: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(matrix)


4:Perform 2×3 Matrix with float values

In [4]:
#Perform 2×3 Matrix with float values

vec = np.array([[4.7, 1.5, 2.7], [2, 5.3, 3.7]])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 5.3 at index 4
Min value: 1.5 at index 1
Length of vector: 2
Sorted vector: [[1.5 2.7 4.7]
 [2.  3.7 5.3]]
Sum of elements: 19.9
Product of elements: 746.5527000000002
Median value: 3.2
Mean value: 3.3166666666666664
Standard deviation: 1.3789085861248702
